"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {Bookmark,ChevronLeft,ChevronRight,Download,Grid2X2,Maximize2,Search,Share2,Volume2,ZoomIn,ZoomOut} from "lucide-react";

type Book={id:string;title:string;pdfUrl:string;background:string;sound:boolean;download:boolean;views:number};
export default function BookViewer({book,embedded=false}:{book:Book;embedded?:boolean}){
  const host=useRef<HTMLDivElement>(null),flip=useRef<any>(null),audio=useRef<HTMLAudioElement|null>(null),soundRef=useRef(book.sound);
  const [loading,setLoading]=useState(true),[error,setError]=useState(""),[page,setPage]=useState(1),[count,setCount]=useState(0),[thumbs,setThumbs]=useState<string[]>([]),[texts,setTexts]=useState<string[]>([]),[showThumbs,setShowThumbs]=useState(false),[zoom,setZoom]=useState(1),[sound,setSound]=useState(book.sound);
  const turnSound=useCallback(()=>{if(!soundRef.current)return;try{const player=audio.current||new Audio("/page-turn.wav");audio.current=player;player.volume=.8;player.currentTime=0;void player.play()}catch{}},[]);
  useEffect(()=>{let cancelled=false;async function load(){try{
    const response=await fetch(book.pdfUrl);if(!response.ok)throw new Error("PDF could not be downloaded.");
    const pdfjs=await import("pdfjs-dist");pdfjs.GlobalWorkerOptions.workerSrc=new URL("pdfjs-dist/build/pdf.worker.min.mjs",import.meta.url).toString();
    const pdf=await pdfjs.getDocument({data:await response.arrayBuffer()}).promise;if(cancelled||!host.current)return;
    const pages:HTMLDivElement[]=[],previews:string[]=[],pageTexts:string[]=[];host.current.innerHTML="";
    for(let n=1;n<=pdf.numPages;n++){const source=await pdf.getPage(n),base=source.getViewport({scale:1}),target=Math.min(3200,Math.max(2100,1100*Math.min(2.5,devicePixelRatio||1))),vp=source.getViewport({scale:target/base.height}),wrap=document.createElement("div"),canvas=document.createElement("canvas");wrap.className="book-page";canvas.width=Math.round(vp.width);canvas.height=Math.round(vp.height);wrap.appendChild(canvas);host.current.appendChild(wrap);pages.push(wrap);const context=canvas.getContext("2d")!;context.imageSmoothingEnabled=true;context.imageSmoothingQuality="high";await source.render({canvas,canvasContext:context,viewport:vp}).promise;const thumb=document.createElement("canvas"),tv=source.getViewport({scale:150/base.width});thumb.width=Math.round(tv.width);thumb.height=Math.round(tv.height);await source.render({canvas:thumb,canvasContext:thumb.getContext("2d")!,viewport:tv}).promise;previews.push(thumb.toDataURL("image/jpeg",.84));const text=await source.getTextContent();pageTexts.push(text.items.map((x:any)=>x.str||"").join(" "))}
    const {PageFlip}=await import("page-flip"),canvas=pages[0].querySelector("canvas")!,mobile=matchMedia("(max-width: 700px)").matches,h=Math.min(mobile?innerHeight-105:innerHeight-125,mobile?900:1000);
    const instance=new PageFlip(host.current,{width:Math.round(h*canvas.width/canvas.height),height:h,size:"stretch",minWidth:240,maxWidth:820,minHeight:340,maxHeight:1100,showCover:true,usePortrait:true,mobileScrollSupport:false,drawShadow:!mobile,maxShadowOpacity:mobile?0:.72,flippingTime:1000,swipeDistance:15});
    instance.loadFromHTML(pages);instance.on("flip",(e:any)=>{setPage(Number(e.data)+1);turnSound()});flip.current=instance;setCount(pdf.numPages);setThumbs(previews);setTexts(pageTexts);setLoading(false);
  }catch(e){console.error(e);setError(e instanceof Error?e.message:"Book could not be opened.");setLoading(false)}}void load();return()=>{cancelled=true;flip.current?.destroy?.()}},[book.pdfUrl,turnSound]);
  const search=()=>{const q=prompt("Search inside this PDF");if(!q)return;const i=texts.findIndex(x=>x.toLowerCase().includes(q.toLowerCase()));if(i<0)return alert("No matching text was found.");flip.current?.flip(i)};
  const share=()=>navigator.share?navigator.share({title:book.title,url:`${location.origin}/book/${book.id}`}):navigator.clipboard.writeText(`${location.origin}/book/${book.id}`);
  return <main className={`standaloneReader ${embedded?"embeddedReader":""}`} style={{background:book.background||"#eaf2f9"}}>
    <div className="standaloneTools"><button className={showThumbs?"active":""} onClick={()=>setShowThumbs(v=>!v)} aria-label="Thumbnails"><Grid2X2/></button><button onClick={search} aria-label="Search"><Search/></button><button aria-label="Bookmark"><Bookmark/></button><button onClick={()=>document.documentElement.requestFullscreen?.()} aria-label="Fullscreen"><Maximize2/></button><button onClick={share} aria-label="Share"><Share2/></button>{book.download&&<a href={book.pdfUrl} download aria-label="Download"><Download/></a>}</div>
    {showThumbs&&<aside className="standaloneThumbs">{thumbs.map((src,i)=><button key={i} onClick={()=>flip.current?.flip(i)} className={page===i+1?"selected":""}><img src={src} alt={`Page ${i+1}`}/><span>{i+1}</span></button>)}</aside>}
    <section className="standaloneStage">{loading&&<div className="viewerNotice">Opening high-quality flipbook…</div>}{error&&<div className="viewerNotice errorNotice">{error}</div>} {!loading&&!error&&<button className="pageArrow prev" onClick={()=>flip.current?.flipPrev()}><ChevronLeft/></button>}<div ref={host} className="publishedBook" style={{transform:`scale(${zoom})`}}/>{!loading&&!error&&<button className="pageArrow next" onClick={()=>flip.current?.flipNext()}><ChevronRight/></button>}</section>
    {!loading&&!error&&<div className="standaloneBottom"><span>{page} / {count}</span><button onClick={()=>setZoom(v=>Math.max(.7,v-.1))}><ZoomOut/></button><span>{Math.round(zoom*100)}%</span><button onClick={()=>setZoom(v=>Math.min(1.35,v+.1))}><ZoomIn/></button><button className={sound?"soundOn":""} onClick={()=>setSound(v=>{soundRef.current=!v;return !v})}><Volume2/></button></div>}
  </main>;
}
